# Generated by Django 5.0.4 on 2026-03-21 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annotation_type', models.CharField(choices=[('note', 'Note'), ('marker', 'Marker'), ('highlight', 'Highlight')], default='note', max_length=20)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('text', models.TextField(blank=True)),
                ('color', models.CharField(default='#FF69B4', max_length=7)),
                ('component_ref', models.CharField(blank=True, help_text="Part name this annotation is attached to (e.g. 'U1')", max_length=50)),
                ('net_ref', models.CharField(blank=True, help_text='Net name this annotation refers to', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='boards.boardfile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['board', 'user'], name='annotations_board_i_605dd4_idx')],
            },
        ),
    ]
