# Generated by Django 5.0.4 on 2026-03-21 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Display name, e.g. 'iPhone 15 Pro'", max_length=255)),
                ('original_filename', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('brand', models.CharField(blank=True, db_index=True, max_length=100)),
                ('model_number', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('cellphone', 'Cellphone'), ('laptop', 'Laptop'), ('tablet', 'Tablet'), ('desktop', 'Desktop'), ('other', 'Other')], db_index=True, default='cellphone', max_length=20)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('enabled', 'Enabled'), ('disabled', 'Disabled'), ('restricted', 'Restricted')], db_index=True, default='enabled', max_length=20)),
                ('min_tier', models.CharField(default='starter', help_text='Minimum subscription tier required. Only applies when status=restricted.', max_length=20)),
                ('s3_key', models.CharField(max_length=500)),
                ('content_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('format', models.CharField(blank=True, max_length=30)),
                ('part_count', models.IntegerField(blank=True, null=True)),
                ('pin_count', models.IntegerField(blank=True, null=True)),
                ('net_count', models.IntegerField(blank=True, null=True)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parse_error', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.IntegerField(default=0)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'board file',
                'verbose_name_plural': 'board files',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['status', 'category'], name='boards_boar_status_7766eb_idx'), models.Index(fields=['brand', 'status'], name='boards_boar_brand_25a559_idx'), models.Index(fields=['content_hash'], name='boards_boar_content_868477_idx')],
            },
        ),
    ]
